### ISSUE TITLE
Registration Info button missing from settings

### ISSUE THREAD

**Issue by halsteadb** [yourhead/lockdown#7]
Hi Isaiah

RW 6.3.8 and current build of RW7

Just purchased, am unable to locate a enter registration area for the reg code after adding LockDown to a site.

Brad

**Comment by yourhead** [comment]
Oops. Missed the button. Will fix immediately. In the meantime, you should be able to get the reg window to show by adding more than one Login/Password

**Comment by halsteadb** [comment]
Perfect, thanks, I had added 1 but not a second and the box popped up as you said :)

Brad Halstead

**Comment by yourhead** [comment]
there's supposed to be a button in the info panel too. it just got left out somehow on this build.
