### ISSUE TITLE
offer a "Logout" button and effectively log out the user

### ISSUE THREAD

**Issue by girlcarew** [yourhead/lockdown#8]
feature request: offer a "Logout" button and effectively log out the user

**Comment by yourhead** [comment]
can you describe more about this?

**Comment by girlcarew** [comment]
I'm assuming that when using lockdown, a customer must "login" to a particular area of the website. He would like to have a way for users to "log out". I can ask the customer for info if that's not descriptive enough.

**Comment by binsen99** [comment]
I really would like to have logout button as well. Otherwise people has to quit the browser to login to other page. Also, Lockdown asks Username & Password twice all the time.

**Comment by yourhead** [comment]
ahhh...   i see....  have a log out button on the site somewhere.

not sure that is really a feasible thing within the RW API.  but we could perhaps provide a code snipped that could be added the sidebar of your site, depending upon your theme, of course.

**Comment by binsen99** [comment]
I use Foundation. Joe Workman makes Page Safe, similar to LD but I need to let people access to the unique files (pages) from unique username & password. Many of them. I need to import them (username, password, expiry, file path) from CSV file which only Lockdown provide such function. I am new here and not sure if this is appropriate topic here...

**Comment by yourhead** [comment]
@binsen99 This is a bug-tracker.  Generally not a very good place for chatting.  😉

I don't mind or anything -- just you'll probably mostly be talking to yourself here.
A bug tracker is generally used to track bugs and feature request.  Each bug or feature like a topic.

If you want to talk about the merits/tradeoffs of the specific products with other folks I'd recommend either Joe's Weaver boards or the RapidWeaver forum.  Both of them have tons of people who chat about that stuff constantly.

If you'd like specific help with our products you should contact support@yourhead.com and Christi will fix you right up.  😃

**Comment by yourhead** [comment]
lockdown has reached end-of-life. there will be no new features added.
